server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**
          filters:
            - AuthenticationFilter

        - id: college-service
          uri: lb://COLLEGE-SERVICE
          predicates:
            - Path=/college/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: ROUTER-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/